### ISSUE TITLE
channel_list / claim_list_mine / claim_list should return claim data

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1483]
## The Issue
Channel_list / claim_list_mine / claim_list needs to return claim data (including supports/tips?) similar to what it used to. Currently, it only shows basic tx information.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Noticed we are also missing height, confirmations, has_signature (need this?), signature_is_valid on claim_list_mine/claim_list. Also missing channel_name on claim_list_mine for claims that have certificates (to be consistent of what was previously available). There also used to be a field called `"decoded_claim": true.` @eukreign said this data will differ from other claim commands since it only comes from the local database - I'd like to discuss this at tomorrow's standup. 

claim_list still shows raw data currently. I'd expect it to show the same data as resolve, but include a list of claims.

**Comment by eukreign** [comment]
`has_signature` is definitely there (but only if the claim represents a channel): https://github.com/lbryio/lbry/blob/master/lbrynet/daemon/json_response_encoder.py#L65

`signature_is_valid`, what does this do?

do you need both `height` and `confirmations`? doesn't the client already know the current best height? could i just return the height at which the claim was made and the client can figure out the confirmations as needed (`claim.height - best_known_height`). `confirmations` is a moving target; seems like it's best to calculate it just as it's about to be shown to the user and using the most recent known blockchain height.

**Comment by tzarebczan** [comment]
Yes, height represents the block the claim was created/updated in - and confirmations would be calculated as you mentioned. 

Below is a sample claim_list_mine entry of a claim with a channel - this also had has_signature (if that's redundant, then we should remove it from all claim related commands). signature is valid checks the signature against the public key of the channel - so if the channel public key changed, the signature would be invalid.  This is available on the resolve command. 

```

 {
    "address": "bHAhxhvRd3fKgkM33cRZRMnxMFc5HjmfQy",
    "amount": 0.1,
    "blocks_to_expiration": 225655,
    "category": "claim",
    "channel_name": "@MyLBRYChannel",
    "claim_id": "b626039cabd667699ff7493daa06085da7fe9482",
    "confirmations": 37319,
    "decoded_claim": true,
    "expiration_height": 675917,
    "expired": false,
    "has_signature": true,
    "height": 412943,
    "is_pending": false,
    "is_spent": false,
    "name": "wallpaper",
    "nout": 0,
    "permanent_url": "@MyLBRYChannel#0e918739eb10338517c072424aacbee908c33091/wallpaper",
    "signature_is_valid": true,
    "txid": "dbf4bcae39fe7566260a6e99ea5af07ede4ec2c12b06d11077a9a6e653f6dd4f",
    "value": {
      "claimType": "streamType",
      "publisherSignature": {
        "certificateId": "0e918739eb10338517c072424aacbee908c33091",
        "signature": "6c6eb854891ad2309328a212b135804947b23d8cdcaaad0ba24e4d20769c9260e9c5176379c11c62287b5f33034076e21d1b51e630154c762402bd75febe5be1",
        "signatureType": "SECP256k1",
        "version": "_0_0_1"
      },
      "stream": {
        "metadata": {
          "author": "",
          "description": "",
          "language": "en",
          "license": "None",
          "licenseUrl": "",
          "nsfw": false,
          "preview": "",
          "thumbnail": "https://spee.ch/379a67d321a9011c17c773a4df457f556f06a037/UwcoDFPqEsPPvvzqyPjLA82o.jpg",
          "title": "Wallpaper",
          "version": "_0_1_0"
        },
        "source": {
          "contentType": "image/jpeg",
          "source": "5e4b7281c21e344717ccd4d0f49c4b3187db4cd42462412e0d80e68c2f59b8f64121877f0d7fd5d1fdce4617ef970846",
          "sourceType": "lbry_sd_hash",
          "version": "_0_0_1"
        },
        "version": "_0_0_1"
      },
      "version": "_0_0_1"
    }
  },
```

**Comment by tzarebczan** [comment]
We also agreed that @shyba will work on claim_list and pass the calls through a resolve in order to properly validate all claims - please create an issue for the correct way we want to handle this in the future and add a comment in the source.

**Comment by tzarebczan** [comment]
@eukreign forgot to mention this missing one in the morning: missing channel_name on claim_list_mine for claims that have certificates

**Comment by alyssaoc** [comment]
has been fixed

**Comment by tzarebczan** [comment]
Reopening, claim_list still does not have claim data. Let @shyba know via Slack.

**Comment by eukreign** [comment]
merged #1679
