### ISSUE TITLE
wallet migration fails with too many addresses

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry#1521]
New migration code pre-generates all addresses and ends up saving them in a single SQL query. This breaks SQLite:

```
2018-10-09 09:53:24,289 ERROR    lbrynet.daemon.Component:61: Error setting up wallet
Traceback (most recent call last):
  File "lbrynet\daemon\Component.py", line 55, in _setup
  File "twisted\internet\defer.py", line 1416, in _inlineCallbacks
  File "twisted\python\failure.py", line 491, in throwExceptionIntoGenerator
  File "lbrynet\daemon\Components.py", line 344, in start
  File "twisted\internet\defer.py", line 1418, in _inlineCallbacks
  File "lbrynet\wallet\manager.py", line 199, in from_lbrynet_config
  File "twisted\internet\defer.py", line 1416, in _inlineCallbacks
  File "twisted\python\failure.py", line 491, in throwExceptionIntoGenerator
  File "lbrynet\wallet\manager.py", line 206, in _migrate_addresses
  File "twisted\internet\defer.py", line 1416, in _inlineCallbacks
  File "twisted\python\failure.py", line 491, in throwExceptionIntoGenerator
  File "torba\baseaccount.py", line 114, in generate_keys
  File "twisted\python\threadpool.py", line 250, in inContext
  File "twisted\python\threadpool.py", line 266, in <lambda>
  File "twisted\python\context.py", line 122, in callWithContext
  File "twisted\python\context.py", line 85, in callWithContext
  File "twisted\enterprise\adbapi.py", line 475, in _runInteraction
  File "twisted\python\compat.py", line 463, in reraise
  File "twisted\enterprise\adbapi.py", line 465, in _runInteraction
  File "twisted\enterprise\adbapi.py", line 484, in _runOperation
sqlite3.OperationalError: too many SQL variables
```

This code needs to be changed to save `new_keys` in batches when there are too many (need to figure out what *too many* means): https://github.com/lbryio/torba/blob/master/torba/baseaccount.py#L113

**Comment by eukreign** [comment]
Fixed in https://github.com/lbryio/torba/pull/19

**Comment by tzarebczan** [comment]
This is still happening to me a on windows machine on .30.1rc1.

**Comment by tzarebczan** [comment]
Nevermind, the Issue I actually ran into right before upgrade is https://github.com/lbryio/lbry/issues/1331 - not sure how this happened on a 2nd install for me - seemed to occur after an abrupt restart of my PC (in 1331, it happened after deleting some files).
