### ISSUE TITLE
older daemon (0.17) fails to migrate properly during migrate5to6.py

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1686]
## The Issue
0.17 daemon upgrading to 0.30, fails on migrate5to6.py

```
2018-11-30 16:51:51,221 INFO     lbrynet.extras.daemon.migrator.migrate4to5:11: Migration succeeded
2018-11-30 16:51:51,222 INFO     lbrynet.extras.daemon.migrator.dbmigrator:30: successfully migrated the database from revision 4 to 5
2018-11-30 16:51:51,321 INFO     lbrynet.extras.daemon.Components:238: Resuming download of 23247952 bytes from s3
2018-11-30 16:51:52,037 INFO     lbrynet.extras.daemon.migrator.migrate5to6:217: migrated 15386 blobs
2018-11-30 16:51:52,252 INFO     lbrynet.extras.daemon.migrator.migrate5to6:267: migrated 115 claims
2018-11-30 16:51:52,257 INFO     lbrynet.extras.daemon.Components:244: fetched headers from s3 (s3 height: 478418), now verifying integrity after download.
2018-11-30 16:51:52,782 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "twisted\internet\defer.py", line 1416, in _inlineCallbacks
  File "twisted\python\failure.py", line 491, in throwExceptionIntoGenerator
  File "lbrynet\extras\daemon\Components.py", line 177, in start
  File "twisted\python\threadpool.py", line 250, in inContext
  File "twisted\python\threadpool.py", line 266, in <lambda>
  File "twisted\python\context.py", line 122, in callWithContext
  File "twisted\python\context.py", line 85, in callWithContext
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 310, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 80, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 272, in _make_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 80, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 193, in _import_file
LookupError: 'hex' is not a text encoding; use codecs.encode() to handle arbitrary codecs
2018-11-30 16:51:52,785 INFO     lbrynet.dht.protocol:199: DHT listening on UDP 4445 (ext port 4445)
2018-11-30 16:51:52,785 INFO     lbrynet.extras.daemon.Components:459: Started the dht
2018-11-30 16:51:52,785 INFO     lbrynet.extras.daemon.Components:366: Starting torba wallet
2018-11-30 16:51:52,800 INFO     lbrynet.extras.wallet.manager:123: Wallet migrator found 191 receiving addresses and 45 change addresses. 236 in total on history.
2018-11-30 16:51:52,887 INFO     torba.client.basedatabase:163: connecting to database: C:\Users\Stan\AppData\Roaming\lbryum\lbc_mainnet\blockchain.db
2018-11-30 16:51:52,920 INFO     lbrynet.dht.node:227: Attempting to join the DHT network, 0 contacts known so far
2018-11-30 16:51:53,287 WARNING  lbrynet.extras.daemon.auth.server:325: error processing api request: 'NoneType' object has no attribute 'count_finished_blobs'
traceback:   File "twisted\internet\defer.py", line 654, in _runCallbacks
    
  File "lbrynet\extras\daemon\auth\server.py", line 96, in trap
    
  File "twisted\python\failure.py", line 439, in trap
    
  File "twisted\python\failure.py", line 467, in raiseException
    
  File "lbrynet\extras\daemon\Daemon.py", line 791, in jsonrpc_status
    
  File "twisted\internet\defer.py", line 1418, in _inlineCallbacks
    
  File "lbrynet\extras\daemon\Components.py", line 408, in get_status
    
builtins.AttributeError: 'NoneType' object has no attribute 'count_finished_blobs'
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Another user ran into the same issue:

```
019-01-02 12:29:25,069 INFO     lbrynet.extras.daemon.Components:175: Upgrading your databases (revision 4 to 9)
2019-01-02 12:29:25,069 INFO     lbrynet.extras.daemon.ExchangeRateManager:212: Starting exchange rate manager
2019-01-02 12:29:25,105 INFO     lbrynet.p2p.RateLimiter:70: Starting rate limiter.
2019-01-02 12:29:25,105 INFO     lbrynet.extras.daemon.Components:776: detecting external ip
2019-01-02 12:29:25,107 INFO     lbrynet.extras.daemon.migrator.migrate4to5:9: Doing the migration
2019-01-02 12:29:25,321 INFO     lbrynet.extras.daemon.migrator.migrate4to5:11: Migration succeeded
2019-01-02 12:29:25,321 INFO     lbrynet.extras.daemon.migrator.dbmigrator:30: successfully migrated the database from revision 4 to 5
2019-01-02 12:29:25,448 INFO     lbrynet.extras.daemon.migrator.migrate5to6:217: migrated 2 blobs
2019-01-02 12:29:25,449 INFO     lbrynet.extras.daemon.migrator.migrate5to6:267: migrated 0 claims
2019-01-02 12:29:25,545 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "twisted\internet\defer.py", line 1416, in _inlineCallbacks
  File "twisted\python\failure.py", line 491, in throwExceptionIntoGenerator
  File "lbrynet\extras\daemon\Components.py", line 177, in start
  File "twisted\python\threadpool.py", line 250, in inContext
  File "twisted\python\threadpool.py", line 266, in <lambda>
  File "twisted\python\context.py", line 122, in callWithContext
  File "twisted\python\context.py", line 85, in callWithContext
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 310, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 80, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 272, in _make_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 80, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 193, in _import_file
LookupError: 'hex' is not a text encoding; use codecs.encode() to handle arbitrary codecs
```

**Comment by tzarebczan** [comment]
And another...we should prioritize this...
```
2019-01-08 10:20:19,395 INFO     lbrynet.extras.daemon.migrator.migrate4to5:11: Migration succeeded
2019-01-08 10:20:19,396 INFO     lbrynet.extras.daemon.migrator.dbmigrator:30: successfully migrated the database from revision 4 to 5
2019-01-08 10:20:19,638 INFO     lbrynet.extras.daemon.Daemon:823: Get version info: {"processor": "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel", "python_version": "3.7.1", "platform": "Windows-10-10.0.17134", "os_release": "10", "os_system": "Windows", "lbrynet_version": "0.30.1", "lbryschema_version": "0.0.16", "build": "release"}
2019-01-08 10:20:19,673 INFO     torba.client.basenetwork:74: Successfully connected to SPV wallet server: lbryumx1.lbry.io:50001
2019-01-08 10:20:19,712 INFO     lbrynet.extras.daemon.migrator.migrate5to6:217: migrated 303 blobs
2019-01-08 10:20:19,721 INFO     lbrynet.extras.daemon.migrator.migrate5to6:267: migrated 5 claims
2019-01-08 10:20:19,727 ERROR    lbrynet.extras.daemon.Component:61: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "twisted\internet\defer.py", line 1416, in _inlineCallbacks
  File "twisted\python\failure.py", line 491, in throwExceptionIntoGenerator
  File "lbrynet\extras\daemon\Components.py", line 177, in start
  File "twisted\python\threadpool.py", line 250, in inContext
  File "twisted\python\threadpool.py", line 266, in <lambda>
  File "twisted\python\context.py", line 122, in callWithContext
  File "twisted\python\context.py", line 85, in callWithContext
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 310, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 80, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 272, in _make_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 80, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 193, in _import_file
LookupError: 'hex' is not a text encoding; use codecs.encode() to handle arbitrary codecs```

**Comment by eukreign** [comment]
fixed in https://github.com/lbryio/lbry/pull/1751

**Comment by tzarebczan** [comment]
Still a problem, but now with a new error. Will DM you the files to reproduce. 
```19-01-09 15:01:22,666 INFO     lbrynet.extras.daemon.migrator.migrate5to6:216: migrated 15386 blobs
2019-01-09 15:01:22,825 INFO     lbrynet.extras.daemon.migrator.migrate5to6:266: migrated 115 claims
2019-01-09 15:01:22,834 ERROR    lbrynet.extras.daemon.Component:60: Error setting up database
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 54, in _setup
  File "lbrynet\extras\daemon\Components.py", line 122, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 309, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 79, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 271, in _make_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 79, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 192, in _import_file
TypeError: a bytes-like object is required, not 'str'
2019-01-09 15:01:22,852 ERROR    asyncio:1597: Task exception was never retrieved
future: <Task finished coro=<ComponentManager.setup.<locals>._setup() done, defined at lbrynet\extras\daemon\ComponentManager.py:122> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "lbrynet\extras\daemon\ComponentManager.py", line 123, in _setup
  File "lbrynet\extras\daemon\Component.py", line 61, in _setup
  File "lbrynet\extras\daemon\Component.py", line 54, in _setup
  File "lbrynet\extras\daemon\Components.py", line 122, in start
  File "concurrent\futures\thread.py", line 57, in run
  File "lbrynet\extras\daemon\migrator\dbmigrator.py", line 28, in migrate_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 309, in do_migration
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 79, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 271, in _make_db
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 79, in _wrapper
  File "lbrynet\extras\daemon\migrator\migrate5to6.py", line 192, in _import_file
TypeError: a bytes-like object is required, not 'str'```

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry/pull/1777
