### ISSUE TITLE
Multi send transactions affecting wallet balance

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2003]
## The Issue
@tiger5226 has created a new program that tips creators based on views. It does so via a multisend tx like: https://explorer.lbry.com/tx/5404c08dd1a1841019ab5db0f31a18ff58ffef649f058f71c6dad643f61a5a12

Shawn was the recipient of such a tip, but it also showed the 2 other links transactions as if he was sending them.

This is also affecting wallet balance. 

<img width="787" alt="what" src="https://user-images.githubusercontent.com/8120721/55241598-cb492180-5211-11e9-8984-0f9b081ec3cd.PNG">

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
This was resolved in new 0.35.0 release and @tzarebczan made a special hot patch build of a previous release with this fix.

**Comment by tzarebczan** [comment]
This is also affecting wallet balance, which is not fixed. Reopening.

**Comment by tzarebczan** [comment]
Nevermind, false alert. Tips don't count towards balance either, so I was just confused. It's fine...
