### ISSUE TITLE
socket.error: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by l2dy** [lbryio/lbry#530]
### Steps to reproduce
1. Start `lbrynet-daemon --verbose` from Terminal

### Expected behaviour
Starts up safely.

### Actual behaviour
Following error reoccurs
```
CRITICAL twisted:154: Unhandled Error
Traceback (most recent call last):
  File "lbry.py", line 5, in <module>

  File "site-packages/lbrynet/lbrynet_daemon/DaemonControl.py", line 77, in start

  File "site-packages/twisted/internet/base.py", line 1199, in run

  File "site-packages/twisted/internet/base.py", line 1208, in mainLoop

--- <exception caught here> ---
  File "site-packages/twisted/internet/base.py", line 828, in runUntilCurrent

  File "site-packages/lbrynet/dht/protocol.py", line 264, in _write_and_remove

socket.error: [Errno 1] Operation not permitted
```

## System Configuration

 

```
[
  {
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.1",
    "lbryum_version": "2.7.13",
    "os_release": "16.4.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.4.0-x86_64-i386-64bit",
    "remote_lbrynet": null,
    "ui_version": "not loaded yet"
  }
]
```

**Comment by lyoshenka** [comment]
Thanks for submitting this. Could you check a few things please:

1 - Are you connected to the internet?
2 - Is anything else running on any of the following ports: 
  - 4444 udp
  - 3333 tcp
  - 5279 tcp

**Comment by l2dy** [comment]
1. Yes.
2. No.
3. I enabled firewall and that might be the cause.

I've downloaded rc5 and it crashed with
```
ERROR    lbrynet.lbryfilemanager.EncryptedFileManager:139: An error occurred while starting a lbry file (2, 296..., None)
Traceback (most recent call last):
  File "site-packages/lbrynet/lbryfilemanager/EncryptedFileManager.py", line 136, in _set_options_and_restore
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbryfilemanager/EncryptedFileDownloader.py", line 66, in restore
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/lbryfilemanager/EncryptedFileDownloader.py", line 125, in load_file_attributes
NoSuchSDHash: b93...
```
reocuuring and
```
ERROR    lbrynet.lbrynet_daemon.DaemonControl:133: Failed to startup
Traceback (most recent call last):
  File "site-packages/lbrynet/lbrynet_daemon/DaemonControl.py", line 129, in start_server_and_listen
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/DaemonServer.py", line 48, in start
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 331, in setup
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 647, in _setup_lbry_file_manager
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/lbryfilemanager/EncryptedFileManager.py", line 61, in setup
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by lyoshenka** [comment]
I fixed the second error in rc6. Can you give that a try please?

**Comment by l2dy** [comment]
I've confirmed that it's the firewall causing `socket.error`. Please handle this gracefully.

This error still reoccurs for a few times but it didn't crash anymore.
```
ERROR    lbrynet.lbryfilemanager.EncryptedFileManager:139: An error occurred while starting a lbry file (2, 296..., None)
Traceback (most recent call last):
  File "site-packages/lbrynet/lbryfilemanager/EncryptedFileManager.py", line 136, in _set_options_and_restore
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbryfilemanager/EncryptedFileDownloader.py", line 66, in restore
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/lbryfilemanager/EncryptedFileDownloader.py", line 125, in load_file_attributes
NoSuchSDHash: b93...
```

**Comment by l2dy** [comment]
Also I get this upon exiting (Ctrl+C) with firewall off.

```
CRITICAL twisted:154: Unhandled Error
Traceback (most recent call last):
  File "daemon.py", line 4, in <module>

  File "site-packages/lbrynet/lbrynet_daemon/DaemonControl.py", line 97, in start

  File "site-packages/twisted/internet/base.py", line 1199, in run

  File "site-packages/twisted/internet/base.py", line 1208, in mainLoop

--- <exception caught here> ---
  File "site-packages/twisted/internet/base.py", line 801, in runUntilCurrent

  File "site-packages/twisted/internet/base.py", line 584, in stop

twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```

**Comment by lyoshenka** [comment]
@l2dy what firewall settings did you have that caused the `socket.error`? it would help us reproduce the issue and make sure we have it fixed.

**Comment by l2dy** [comment]
In two situations (both blocking incoming connections for lbrynet-daemon):

1. Turn on Firewall when lbrynet-daemon is running.
2. Start lbrynet-daemon when firewall is on.

Note that there's some delay until error occurs.

**Comment by lyoshenka** [comment]
I broke out the ReactorNotRunning: #544 

We'll have the daemon check the ports its binding so it knows they are available and there are no firewall issues.

**Comment by lyoshenka** [comment]
Moved the issue to https://github.com/lbryio/lbry/issues/710
